# Generated by ChatGPT on 2025-11-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torimoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='consumed_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
    ]
